### ISSUE TITLE
Getting probability of sentiment categories

### ISSUE THREAD

**Issue by sadettindemirel** [ViralLab/TurkishBERTweet#1]
Hi,
Could you please add probability of sentiment categories or show how to get the probability scores of the categories.
e.g.
`{'label': 'positive', 'probability': {'negative': 0.004584966693073511, 'neutral': 0.19360853731632233, 'positive': 0.8018065094947815}}`

**Comment by axen1** [comment]
File "c:/Users/bahad/OneDrive/Masaüstü/TurkishBERTweet-main/Preprocessor/preprocessor.py", line 5, in <module>
    from urlextract import URLExtract
ModuleNotFoundError: No module named 'urlextract'

**Comment by AliNajafi1998** [comment]
@axen1 You need to install the required dependencies. The commands for the installation are already listed in the README file.

**Comment by AliNajafi1998** [comment]
@sadettindemirel 

Haven't run the following code myself, but it should do the job!

```
with torch.no_grad():
    for s in preprocessed_texts:
        ids = tokenizer.encode_plus(s, return_tensors="pt")
        logits = turkishBERTweet_sa(**ids).logits 
        probs = torch.softmax(logits)
        print(s)
        for i in range(len(id2label_sa)):
            print(id2label_sa[label_id],":", probs[i])
```
